### ISSUE TITLE
"CONDA_DIR"

### ISSUE THREAD

**Issue by bjornjorgensen** [b-data/jupyterlab-python-docker-stack#3]
I don't think this will work 
https://github.com/b-data/jupyterlab-python-docker-stack/blob/074d2b2ff4db0d8b0f209ecb2967959b48ecc416/base/conf/jupyter/etc/jupyter/jupyter_server_config.py#L69

**Comment by benz0li** [comment]
It does.

*In Python*:

```python
>>> import os
>>> cnf_file = os.path.join(os.getenv("CONDA_DIR", "/usr/lib"), "ssl", "openssl.cnf")
>>> cnf_file
'/usr/lib/ssl/openssl.cnf'
```

*In Terminal*

```bash
cat /usr/lib/ssl/openssl.cnf

#
# OpenSSL example configuration file.
# See doc/man5/config.pod for more info.
#
# This is mostly being used for generation of certificate requests,
# but may be used for auto loading of providers
...
```

**Comment by bjornjorgensen** [comment]
ok, so it defaults to "/usr/lib" but what about removing  "CONDA_DIR" ?

**Comment by benz0li** [comment]
> ok, so it defaults to "/usr/lib" but what about removing "CONDA_DIR" ?

Will do so when updating to JupyterLab 4.x. Also including https://github.com/jupyter/docker-stacks/pull/1984.

I have not yet updated to JupyterLab 4.x, because some essential extensions are not yet compatible.  
ℹ️ See https://github.com/jupyterlab/jupyterlab/issues/14590 for more information.

**Comment by bjornjorgensen** [comment]
ok, what are those essential extensions?

**Comment by benz0li** [comment]
> ok, what are those essential extensions?

* `jupyter-server-proxy`
* `jupyterlab-git`
* `jupyterlab-lsp`

See https://github.com/b-data/jupyterlab-python-docker-stack/blob/074d2b2ff4db0d8b0f209ecb2967959b48ecc416/base/latest.Dockerfile#L227-L237

**Comment by bjornjorgensen** [comment]
ok, thank you.
Well, my idea it to use debian testing or unstable, have it with python 3.12 RC (for testing) and java 21. Remove coder-server and only have a basic jupyterlab and not having GPU stuff. I use [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/) as IDE and the docker files are on a server. So I connect to it with remote ssh.

**Comment by benz0li** [comment]
> Well, my idea it to use debian testing or unstable, have it with python 3.12 RC (for testing) and java 21. Remove coder-server and only have a basic jupyterlab and not having GPU stuff. I use [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/) as IDE and the docker files are on a server. So I connect to it with remote ssh.

Then, it is better you build on https://github.com/b-data/python-docker-stack. 

Be aware of https://github.com/b-data/python-docker-stack/blob/main/ver/latest.Dockerfile#L9 and that there is neither
`glcr.b-data.ch/python/psi/3.12.0rc<n>/debian:testing` nor
`glcr.b-data.ch/python/psi/3.12.0rc<n>/debian:unstable`

**Comment by benz0li** [comment]
> Then, it is better you build on https://github.com/b-data/python-docker-stack.

That is what I do for the Data Science Dev Containers: https://github.com/b-data/data-science-devcontainers

**Comment by benz0li** [comment]
> Will do so when updating to JupyterLab 4.x. Also including [jupyter/docker-stacks#1984](https://github.com/jupyter/docker-stacks/pull/1984).

Not including https://github.com/jupyter/docker-stacks/pull/2006 and https://github.com/jupyter/docker-stacks/pull/2007, though.  
👉 I.e. not going to migrate startup scripts and hooks to Python.

**Comment by benz0li** [comment]
Closed by https://github.com/b-data/jupyterlab-python-docker-stack/commit/536a918acb32f393338ff7f0c19765a30f02cc76
