### ISSUE TITLE
export PIP_BREAK_SYSTEM_PACKAGES=1

### ISSUE THREAD

**Issue by bjornjorgensen** [b-data/jupyterlab-python-docker-stack#6]
Hi, I have made a Dockerfile for running spark from master branch with debian testing and removed conda.

Insted of `export PIP_BREAK_SYSTEM_PACKAGES=1`

I'm using
# As root user create the virtual environment
RUN python3.11 -m venv /opt/venv && \
    chown -R ${NB_UID}:${NB_GID} /opt/venv

# Switch to the jovyan user
USER "${NB_USER}"
WORKDIR "/home/${NB_USER}"

# Set the PATH to include the virtual environment's executables
ENV PATH="/opt/venv/bin:${PATH}"

# Install packages using pip in the virtual environment
RUN pip install --no-cache-dir --upgrade \  

for more https://github.com/bjornjorgensen/test/blob/main/driver/Dockerfile

**Comment by benz0li** [comment]
@bjornjorgensen This is also what our dear colleagues from the [Rocker project](https://github.com/rocker-org/rocker-versioned2) are heading for.  
ℹ️ For more information, see https://github.com/rocker-org/rocker-versioned2/issues/670.

b-data's/my [JupyterLab] Python docker stack uses a different approach, i.e. copying Python from image [`glcr.b-data.ch/python/psi`](https://gitlab.b-data.ch/python/psi/container_registry). See also https://github.com/rocker-org/rocker-versioned2/issues/670#issuecomment-1600863135.  
👉 This happens while building [`glcr.b-data.ch/python/ver`](https://gitlab.b-data.ch/python/ver/container_registry); the latter being the parent image of [`glcr.b-data.ch/jupyterlab/python/base`](https://gitlab.b-data.ch/jupyterlab/python/base/container_registry).

**Comment by bjornjorgensen** [comment]
oh.. thank you.. 👍

**Comment by benz0li** [comment]
I introduced this for b-data's/my JupyterLab docker stack to allow building with system's python.

I have to admit that this has no actual use with the [JupyterLab] Python docker stack.

I blindly copy-pasted to all of b-data's/my JupyterLab docker stacks.
