### ISSUE TITLE
Multiple environments?

### ISSUE THREAD

**Issue by kallegrens** [b-data/jupyterlab-python-docker-stack#7]
Hello!

I am currently investigating how I can use custom environments in a GPU-enabled Jupyterlab image. I have looked at this repo and also the one from iot-salzburg. It seems none supports this. Do I understand correctly? Any suggestions?

**Comment by benz0li** [comment]
> I am currently investigating how I can use custom environments in a GPU-enabled Jupyterlab image.

What do you mean by [multiple] *custom environments*?

**Comment by benz0li** [comment]
Should you mean Python/Conda environments: You can install [Conda](https://github.com/conda/conda) / [Mamba](https://github.com/mamba-org/mamba) at *user level* when using b-data's/my images.

**Comment by kallegrens** [comment]
Yes, I was thinking custom conda environments which only contain the packages I need.

I have not tried your image yet. The iot-salzburg image is my only reference so far, but I find their conda env too bloated. And I failed to use the new ones I created. 

What steps would be taken to achieve this? I suspect it will not just be to install conda and go as usual.

**Comment by benz0li** [comment]
> What steps would be taken to achieve this? I suspect it will not just be to install conda and go as usual.

"install conda and go as usual" *at runtime and at user level*, i.e. https://docs.conda.io/projects/miniconda/en/latest/index.html#quick-command-line-install (Linux), *should* work as expected when using b-data's/my images.
